service: uploadservice
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  memorySize: 256
  apiGateway:
      binaryMediaTypes:
        - 'image/*'
  stage: dev
  region: us-east-1
  environment:
    BUCKET_ID: !Ref UploadImageStorage

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        # - "s3:PutObjectAcl"
        # - "s3:GetBucketLocation"
      Resource: 
        - Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - "Ref" : "UploadImageStorage"
              - "/*"
        - Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - "Ref" : "UploadImageStorage"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  upload:
    handler: bin/uploadS3
    events:
      - http:
          path: upload
          method: post
  afterupload:
    handler: bin/triggerS3
    events:
      - s3:
          bucket: !Ref UploadImageStorage
          event: s3:ObjectCreated:*
          existing: true


resources:
  Resources:
    UploadImageStorage:
      Type: AWS::S3::Bucket
    
    # ImageTable:
    #   Type: AWS::DynamoDB::Table
    #   Properties:
    #     AttributeDefinitions:
    #       - AttributeName: ID
    #         AttributeType: S
    #     KeySchema:
    #       - AttributeName: ID
    #         KeyType: HASH
    #     BillingMode: PAY_PER_REQUEST
