service: uploadservice
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  memorySize: 128
  apiGateway:
      binaryMediaTypes:
        - 'multipart/form-data'
  stage: dev
  region: us-east-1
  environment:
    UPLOAD_IMAGE_STORAGE_ID: !Ref UploadImageStorage
    ANALYZE_IMAGE_QUEUE_URL: !Ref AnalyzeImageQueue
    TEXTRACT_QUEUE_URL: !Ref TextractQueue
    TEXTRACT_SNS_TOPIC_ARN: !Ref AmazonTextractSNSTopic
    TEXTRACT_ROLE_ARN: !GetAtt AmazonTextractRole.Arn
    IMAGE_TABLE: !Ref ImageTable
  role: defaultRole
  
package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  upload:
    handler: bin/uploadS3
    events:
      - http:
          path: document
          method: post
          cors: true 
  # after_upload:
  #   handler: bin/triggerS3
  #   events:
  #     - s3:
  #         bucket: !Ref UploadImageStorage
  #         event: s3:ObjectCreated:*
  #         existing: true
  # analyze:
  #   handler: bin/analyze
  #   events:
  #     - sqs:
  #         arn: !GetAtt AnalyzeImageQueue.Arn
  # after_analyze:
  #   handler: bin/afteranalyze
  #   events:
  #     - sqs:
  #         arn: !GetAtt TextractQueue.Arn

resources:
  - ${file(config/resources/default-role.yml)}
  - ${file(config/resources/textract-sns-role.yml)}
  - ${file(config/resources/app-resources.yml)}
