service: uploadservice
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  memorySize: 256
  apiGateway:
      binaryMediaTypes:
        - 'image/*'
  stage: dev
  region: us-east-1
  environment:
    UPLOAD_IMAGE_STORAGE_ID: !Ref UploadImageStorage
    ANALYZE_IMAGE_QUEUE_URL: !Ref AnalyzeImageQueue
    TEXTRACT_QUEUE_URL: !Ref TextractQueue
    TEXTRACT_SNS_ARN: !Ref AmazonTextractSNSTopic
    IMAGE_TABLE: !Ref ImageTable
    # MOCK_AI: true
  role: defaultRole
  
package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  upload:
    handler: bin/uploadS3
    events:
      - http:
          path: upload
          method: post
  afterupload:
    handler: bin/triggerS3
    events:
      - s3:
          bucket: !Ref UploadImageStorage
          event: s3:ObjectCreated:*
          existing: true
  analyze:
    handler: bin/analyze
    events:
      - sqs:
          arn: !GetAtt AnalyzeImageQueue.Arn

resources:
  - ${file(config/resources/default-role.yml)}
  - ${file(config/resources/textract-sns-role.yml)}
  - ${file(config/resources/app-resources.yml)}
