service: uploadservice
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  memorySize: 256
  apiGateway:
      binaryMediaTypes:
        - 'image/*'
  stage: dev
  region: us-east-1
  environment:
    UPLOAD_IMAGE_STORAGE_ID: !Ref UploadImageStorage
    ANALYZE_IMAGE_QUEUE_URL: !Ref AnalyzeImageQueue
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetBucketLocation"
      Resource: 
        - Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - "Ref" : "UploadImageStorage"
              - "/*"
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
        - "sqs:SetQueueAttributes"
      Resource: 
        - !GetAtt AnalyzeImageQueue.Arn

  
package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  upload:
    handler: bin/uploadS3
    events:
      - http:
          path: upload
          method: post
  afterupload:
    handler: bin/triggerS3
    events:
      - s3:
          bucket: !Ref UploadImageStorage
          event: s3:ObjectCreated:*
          existing: true

resources:
  Resources:
    UploadImageStorage:
      Type: AWS::S3::Bucket
    AnalyzeImageQueue:
      Type: AWS::SQS::Queue
      Properties: 
        QueueName: AnalyzeImageQueue
        DelaySeconds: 0
    
    # ImageTable:
    #   Type: AWS::DynamoDB::Table
    #   Properties:
    #     AttributeDefinitions:
    #       - AttributeName: ID
    #         AttributeType: S
    #     KeySchema:
    #       - AttributeName: ID
    #         KeyType: HASH
    #     BillingMode: PAY_PER_REQUEST
