Resources:
  UploadImageStorage:
    Type: AWS::S3::Bucket

  AnalyzeImageQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: AnalyzeImageQueue
      DelaySeconds: 0

  TextractQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: TextractQueue
      DelaySeconds: 0
  TextractQueuePolicy: 
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues: 
        - !Ref TextractQueue
      PolicyDocument: 
        Statement:
        - Effect: Allow
          Action: sqs:SendMessage
          Principal: "*"
          Resource: !GetAtt TextractQueue.Arn
          Condition:
            ArnEquals:
              aws:SourceArn: !Ref AmazonTextractSNSTopic
  AmazonTextractSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !GetAtt TextractQueue.Arn
          Protocol: "sqs"
      TopicName: "AmazonTextractSNSTopic"

  ImageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: Timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: TimestampIndex
          KeySchema:
            - AttributeName: Id
              KeyType: HASH
            - AttributeName: Timestamp
              KeyType: RANGE
          Projection: 
            ProjectionType: KEYS_ONLY
      BillingMode: PAY_PER_REQUEST
