Resources:    
  UploadImageStorage:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
  UploadImageStoragePolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref UploadImageStorage
                - /*
      Bucket: !Ref UploadImageStorage

  AnalyzeImageQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: AnalyzeImageQueue
      DelaySeconds: 0

  TextractQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: TextractQueue
      DelaySeconds: 0
  TextractQueuePolicy: 
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues: 
        - !Ref TextractQueue
      PolicyDocument: 
        Statement:
        - Effect: Allow
          Action: sqs:SendMessage
          Principal: "*"
          Resource: !GetAtt TextractQueue.Arn
          Condition:
            ArnEquals:
              aws:SourceArn: !Ref AmazonTextractSNSTopic
  AmazonTextractSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !GetAtt TextractQueue.Arn
          Protocol: "sqs"
      TopicName: "AmazonTextractSNSTopic"

  ImageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: InsertionDate
          AttributeType: S
        - AttributeName: UserId
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIdInsertionDateIndex
          KeySchema:
            - AttributeName: UserId
              KeyType: HASH
            - AttributeName: InsertionDate
              KeyType: RANGE
          Projection: 
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
